name: 'Publish Pilet'
description: 'Builds and publishes a pilet to some feed.'
branding:
  icon: package
  color: green
inputs:
  feed:
    description: 'The target feed name or feed service URL.'
    required: true
    default: 'sample'
  api-key:
    description: 'The API key to use for publishing the pilet.'
    required: false
    default: ''
  bundler:
    description: 'The bundler to use if nothing is specified in the code.'
    required: false
    default: 'parcel'
  base-dir:
    description: 'The base directory relative to the project root.'
    required: false
    default: '.'
outputs:
  version:
    description: 'The published version.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.feed }}
    - ${{ inputs.api-key }}
    - ${{ inputs.bundler }}
    - ${{ inputs.api-base-dir }}
